apiVersion: apps/v1
kind: Deployment
metadata:
  name: joboonja-front-deployment
  namespace: ali-edalat-ns
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  replicas: 3
  selector:
    matchLabels:
      app: joboonja-front
  template:
    metadata:
      labels:
        app: joboonja-front
    spec:
      containers:
        - image: quay.io/aliedalat/frontend
          imagePullPolicy: Always
          name: joboonja-front
          ports:
            - containerPort: 5000
          resources:
              limits:
                memory: "333Mi"
                cpu: "333m"
              requests:
                memory: "100Mi"
                cpu: "100m"
